services:
  searxng:
    build:
      context: .
      dockerfile: searxng.dockerfile
    expose:
      - 4000
    ports:
      - 4000:8080
    networks:
      - perplexica-network

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    # restart: always
    volumes:
      - ./:/home/perplexica
      - /home/perplexica/dist
      - /home/perplexica/src
    depends_on:
      - searxng
    expose:
      - 3001
    # exposes port 3001 and maps it to port 3001 on the container.
    ports:
      - 3001:3001
    networks:
      - perplexica-network

  perplexica-frontend:
    build:
      context: .
      # built using app.dockerfile
      dockerfile: app.dockerfile
      # defines arguments with specific values
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
    # restart: always
    volumes:
      - ./:/home/perplexica
      - /home/perplexica/node_modules
      - /home/perplexica/.next

    depends_on:
      - perplexica-backend
    expose:
      - 3002
    ports:
      # exposes port 3002 and maps it to port 3000 on the container.
      - 3002:3000
    networks:
      - perplexica-network

networks:
  perplexica-network:
